apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grokbot.fullname" . }}-config
  labels:
    {{- include "grokbot.labels" . | nindent 4 }}
stringData:
  DISCORD_TOKEN: {{ .Values.discord.token }}
  DISCORD_STATUS: {{ .Values.discord.status }}
  DISCORD_PREFIX: {{ .Values.discord.prefix }}
  OLLAMA_URL: {{ .Values.ollama.url }}
  OLLAMA_MODEL: {{ .Values.ollama.model }}
  OLLAMA_SYSTEM_PROMPT: {{ .Values.ollama.systemPrompt }}